# a7

 ## とりあえず、bugは修正しましたが、/main/models.pyの内容を各自、確認してください。
